### ISSUE TITLE
当前环节提交后，用户指定下环节的执行人，有没实现不

### ISSUE THREAD

**Issue by lizige** [bluejoe2008/openwebflow#6]
当前环节提交后，用户指定下环节的执行人，有没实现不

**Comment by lisheng007** [comment]
可以，下一个节点的assignee设置一个流程变量，当前节点审批时提交对应的流程变量即可

**Comment by lizige** [comment]
> 可以，下一个节点的assignee设置一个流程变量，当前节点审批时提交对应的流程变量即可
下个节点
